<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-4VMP8RJ" name="com.siliconelabs.qa.tests.LoginPageTest" tests="7" failures="1" timestamp="22 Mar 2021 20:03:24 GMT" time="45.576" errors="0">
  <testcase name="invalidloginTest" time="5.840" classname="com.siliconelabs.qa.tests.LoginPageTest"/>
  <testcase name="invalidloginTest" time="5.801" classname="com.siliconelabs.qa.tests.LoginPageTest"/>
  <testcase name="invalidloginTest" time="7.378" classname="com.siliconelabs.qa.tests.LoginPageTest"/>
  <testcase name="invalidloginTest" time="6.149" classname="com.siliconelabs.qa.tests.LoginPageTest"/>
  <testcase name="loginPageTitleTest" time="6.868" classname="com.siliconelabs.qa.tests.LoginPageTest">
    <failure type="java.lang.AssertionError" message="expected [OrangeHR] but found [OrangeHRM]">
      <![CDATA[java.lang.AssertionError: expected [OrangeHR] but found [OrangeHRM]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.siliconelabs.qa.tests.LoginPageTest.loginPageTitleTest(LoginPageTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- loginPageTitleTest -->
  <testcase name="invalidloginTest" time="5.974" classname="com.siliconelabs.qa.tests.LoginPageTest"/>
  <testcase name="LoginTest" time="7.566" classname="com.siliconelabs.qa.tests.LoginPageTest"/>
</testsuite> <!-- com.siliconelabs.qa.tests.LoginPageTest -->
